### PR TITLE
Add target label to the cleaned data

### PR DESCRIPTION
**Pull request by sfwatanabe**
This PR adds a target label to the cleaned data in preparation for creating train/valid/test splits of each symbol.
- Labels are {-1, 0, 1} to represent sell/hold/buy
    - Can be changed to 0, 1, 2 if preferred
    - Looks at next day rate of change
- Use of pandas for a bit simpler processing of dropping cleaned data to csv, adjusting datatypes
    - Could look at splitting data and labels into separate files
    - Could look at omitting the datetime column if we find it to be redundant

### CODE REVIEW

**Comment by sfwatanabe** [comment]
Changed to y \in {0, 1, 2} to play nice with argmax indexing later down the line

**Comment by killyosaur** [comment]
Asking a quick question as it may be relevant may not be (though possibly not relevant right now?) Are we gong to want  to one-hot encode these values at some point? Trying to determine if the scoring makes sense as buying is the ideal at a stocks low end (or during a downward trend, with the assumption it will eventually go back up), selling makes the most sense during an upward trend (ideally near its peak), and holding is generally considered best practice in long term investments, especially with reasonably stable, slow growth stocks...

**Comment by sfwatanabe** [comment]
> Asking a quick question as it may be relevant may not be (though possibly not relevant right now?) Are we gong to want to one-hot encode these values at some point? Trying to determine if the scoring makes sense as buying is the ideal at a stocks low end (or during a downward trend, with the assumption it will eventually go back up), selling makes the most sense during an upward trend (ideally near its peak), and holding is generally considered best practice in long term investments, especially with reasonably stable, slow growth stocks...

Good question - with respect to one hot I'm assuming you mean for the target class labels? I'm not sure we'll need a one-hot as they're mutually exclusive, however we would need to translate an arbitrary series of predictions to a strategy.


For example - we run a sequence of label predictions and get
- [ 2, 1, 1, 1, 2]

We notice that we're already holding stock from timestep 0 when we see the second buy signal. We can either choose to double down (up to some available cash position) or simply treat it as a non-signal since we're already holding.

I've done some basic strategy via ML4T that may or may not apply to our problem, but I think it might be able to help from a practical perspective.

**Comment by anarasimham** [comment]
Thinking about the labels a bit more - it looks like you're saying "if stock falls beyond daily threshold, let's sell". Aren't there multi-day windows we could consider for a label? What if it falls for a day then rises? Maybe I am over-complicating, we can always KISS as well for this basic project. There could be things like cool-down periods for taking actions, sell thresholds (sell after you've lost 20% of value).

Overall question - Is the label we are assigning here baking in a lot of assumptions?

**Comment by sfwatanabe** [comment]
> Thinking about the labels a bit more - it looks like you're saying "if stock falls beyond daily threshold, let's sell". Aren't there multi-day windows we could consider for a label? What if it falls for a day then rises? Maybe I am over-complicating, we can always KISS as well for this basic project. There could be things like cool-down periods for taking actions, sell thresholds (sell after you've lost 20% of value).
> 
> Overall question - Is the label we are assigning here baking in a lot of assumptions?

Re overall:  yes we're baking in some assumptions here for sure. You could view the method of assigning the label as a black box and we can change it to something more complex. The thought here was to act as a proxy for a single day price move. 

This is intended as a starting point, we could refactor to allow for different methods of label assignment as well.   For now, just trying to get something tangible up to work with. One of the transformer papers used a similar approach, but only predicted of the stock was going up or down.

**Comment by killyosaur** [comment]
It may not be a bad idea, as you said in the earlier post, to move the targets to a separate file. Will make any changes to that less painful in the future, limits our refactor costs (especially as we only have about 4 weeks to pull this all off :D ).

**Comment by sfwatanabe** [comment]
> Thinking about the labels a bit more - it looks like you're saying "if stock falls beyond daily threshold, let's sell". Aren't there multi-day windows we could consider for a label? What if it falls for a day then rises? Maybe I am over-complicating, we can always KISS as well for this basic project. There could be things like cool-down periods for taking actions, sell thresholds (sell after you've lost 20% of value).
> 
> Overall question - Is the label we are assigning here baking in a lot of assumptions?

Perhaps we could keep this as a stretch goal?

**Review by killyosaur — APPROVED** [review]

**Pull request merged**
