### PR TITLE
Add financial indicators, small cleanup

### PR DESCRIPTION
**Pull request by sfwatanabe**
This PR adds 11 financial indicators to the datasets before splitting into train/valid/test
- Simple & Exponential moving averages
- %B
- MACD Histogram
- Momentum (ROC)
- Relative Volume
- Relative Strength Index (RSI)

These will be computed and added to the dataset as part of the `create_datasets` call
- Added default date ranges for train/valid/test instead of percentage splits
- Simplified the args to create datasets, should just be a simple call
- Added a fixed scaling option for the Year/Month/Day columns
    - Mostly related to time2vec things, can move out if needed

If there are any other indicators you'd like to see added please let me know and we can get it rolled into this PR.

Lastly - please yell at me if this is too much.

### CODE REVIEW

**Comment by anarasimham** [comment]
LGTM - reviewed some of the indicator logic and I am familiar with most of the indicators being used; in the ethos of going 0->1 we should get something running and then iterate to improve. I'm sure we will find other indicators down the road to add in but don't have those at the moment.

**Comment by sfwatanabe** [comment]
I'll resolve the merge conflicts and get this pulled into main later today

**Comment by sfwatanabe** [comment]
> LGTM - reviewed some of the indicator logic and I am familiar with most of the indicators being used; in the ethos of going 0->1 we should get something running and then iterate to improve. I'm sure we will find other indicators down the road to add in but I don't have suggestions at the moment.
> 
> Don't see a button to "approve", perhaps I don't have permissions? I figure the PR writer should be the one to merge

Yes - this would be normal best practice to have the PR writer make the merge unless you're in a situation where branches are extremely locked down.

**Review by killyosaur — APPROVED** [review]

**Comment by killyosaur** [comment]
I didn't place any restrictions on anyone to merge. just need an approval to do so...

**Comment by anarasimham** [comment]
That’s what I mean, I don’t see a way to approve

Ashish

**Comment by killyosaur** [comment]
> That’s what I mean, I don’t see a way to approve Ashish
> […](#)

Ah. so when you click on the changed files tab at the top to view the changes, you are not seeing the green "review changes "  dropdown button?

**Pull request merged**
